config/routes.rb
BulkUploader::Application.routes.draw do
  
  resources :orders

  get 'users/login'
  post 'users/login'
  
  get 'whatelse/get_started'
  get 'whatelse/error'
  get 'whatelse/download'
  
  get 'orders/index'
  get 'line_items/index'
  
  get 'companies/index'
  get 'companies/clear_all'
  get 'companies/download_all'
  get 'companies/copy_from_dfp'
  resources :companies do
    get 'show', :on => :member
  end

  get 'labels/index'
  get 'labels/clear_all'
  get 'labels/download_all'
  get 'labels/copy_from_dfp'
  resources :labels do
    get 'show', :on => :member
  end

  get 'ad_units/index'
  get 'ad_units/clear_all'
  get 'ad_units/download_all'
  get 'ad_units/copy_from_dfp'
  resources :ad_units do
    get 'show', :on => :member
  end

  get 'uploads/clear_all'
  resources :uploads do
    get 'download_errors', :on => :member
    get 'download_created', :on => :member
    get 'download_not_created', :on => :member    
  end
    
  root :to => 'whatelse#get_started'

end

app/models/label.rb
class Label < ActiveRecord::Base
	
	validates :name, :presence => true, 
	                 :uniqueness => { :case_sensitive => false, :scope => [:network_id, :label_type] },
	                 :length => {:maximum => 127 }
	validate :label_type_value_is_permitted

	has_and_belongs_to_many :companies

  LABEL_TYPES = ['COMPETITIVE_EXCLUSION', 'AD_UNIT_FREQUENCY_CAP']

  scope :nw, lambda { |network_id| where( :network_id => network_id) }
  
  def self.params_dfp2bulk(p)
    debugger
    params = p.dup
    params[:label_type] = params.delete(:type)
    params[:dfp_id] = params.delete(:id).to_s
    params.delete(:is_active)
    return params
  end
  
  def params_bulk2dfp
    params = {}
    params[:name] = self.name
    params[:description] = self.description
    params[:type] = self.label_type
    return params
  end

	def self.row_to_params(row, nw_id)
		params = {}
		params[:name] = row[0]
		params[:description] = row[1]
		params[:label_type] = row[2].sub(' ','') unless row[2].nil?
		params[:network_id] = nw_id
    return params
	end

  def to_row
    row = [self.name, self.description, self.label_type]
  end

  def exists?
    if Label.find_by_name(self.name)
      return true
    else
      return false
    end
  end
  
  def self.get_statement
    statement = {
        :query => "WHERE type IN ('COMPETITIVE_EXCLUSION', 'AD_UNIT_FREQUENCY_CAP') ORDER BY name LIMIT 500"
    }
  end
  
  protected
  def label_type_value_is_permitted
		unless Label::LABEL_TYPES.include?(label_type)
			errors.add(:label_type, 'Permitted values are COMPETITIVE_EXCLUSION and AD_UNIT_FREQUENCY_CAP.')
		end
	end
	
	def remove_trailing_spaces
    self.name.chop! while self.name.last == ' '
    self.name.reverse!.chop!.reverse! while self.name.first == ' '
  end
  
  def self.sort_all(labels)
    labels.sort! do |a,b|
      a.name <=> b.name
    end
  end

end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  # GET /labels
  # GET /labels.json
  def index
    @labels = Label.nw(session[:nw]).all
    Label.sort_all(@labels)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @labels }
    end
  end

  # GET /labels/1
  # GET /labels/1.json
  def show
    @label = Label.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @label }
    end
  end

  # GET /labels/new
  # GET /labels/new.json
  def new
    @label = Label.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @label }
    end
  end

  # GET /labels/1/edit
  def edit
    @label = Label.find(params[:id])
  end

  # POST /labels
  # POST /labels.json
  def create
    @label = Label.new(params[:label])

    respond_to do |format|
      if @label.save
        format.html { redirect_to @label, notice: 'Label was successfully created.' }
        format.json { render json: @label, status: :created, location: @label }
      else
        format.html { render action: "new" }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /labels/1
  # PUT /labels/1.json
  def update
    @label = Label.find(params[:id])

    respond_to do |format|
      if @label.update_attributes(params[:label])
        format.html { redirect_to @label, notice: 'Label was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1
  # DELETE /labels/1.json
  def destroy
    @label = Label.find(params[:id])
    @label.destroy

    respond_to do |format|
      format.html { redirect_to labels_url }
      format.json { head :ok }
    end
  end
  
  def download_all
    super
  end
  
  def copy_from_dfp
    super
  end
  
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<%= twitter_bootstrap_form_for(@label) do |f| %>
	<%=f.inputs 'Label', :class => 'Label' do %>
    <%= f.text_field :name %>
    <%= f.text_area :description, :rows => 4 %><br />
    <%= f.select 'label_type', 'Label Type', Label::LABEL_TYPES, :input_html => { :include_blank => false }  %>
	<% end %>
	<%= f.actions do %>
    <%= f.submit %>
	<% end %>
<% end %>

app/views/labels/edit.html.erb
<h1>Editing label</h1>

<%= render 'form' %>

<%= link_to 'Details', @label %> |
<%= link_to 'Back', labels_path %>

app/views/labels/index.html.erb
<%= render 'layouts/action_bar'%>
<table class="zebra-striped bordered-table super-condensed-table green">
	<thead>
	  <tr>
	    <th>Name</th>
	    <th>Type</th>
	    <th>Description</th>
	    <th>Uploaded to DFP?</th>
	    <th>Actions</th>
	  </tr>
	</thead>
	<tbody>
		<% @labels.each do |label| %>
		  <tr>
		    <td><%= label.name %></td>
		    <td><%= label.label_type %></td>
		    <td><%= label.description %></td>
			<td><%= label.dfp_id.blank? ? "No" : "Yes" %></td>	
		    <td><%= link_to 'Details', label %>
		  </tr>
		<% end %>
	</tbody>
</table>

app/views/labels/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', labels_path %>

app/views/labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @label.name %>
</p>

<p>
  <b>Description:</b>
  <%= @label.description %>
</p>

<p>
  <b>Type:</b>
  <%= @label.label_type %>
</p>


<%= link_to 'Edit', edit_label_path(@label) %> |
<%= link_to 'Back', labels_path %>