config/routes.rb
BulkUploader::Application.routes.draw do
  
  resources :orders

  get 'users/login'
  post 'users/login'
  
  get 'whatelse/get_started'
  get 'whatelse/error'
  get 'whatelse/download'
  
  get 'orders/index'
  get 'line_items/index'
  
  get 'companies/index'
  get 'companies/clear_all'
  get 'companies/download_all'
  get 'companies/copy_from_dfp'
  resources :companies do
    get 'show', :on => :member
  end

  get 'labels/index'
  get 'labels/clear_all'
  get 'labels/download_all'
  get 'labels/copy_from_dfp'
  resources :labels do
    get 'show', :on => :member
  end

  get 'ad_units/index'
  get 'ad_units/clear_all'
  get 'ad_units/download_all'
  get 'ad_units/copy_from_dfp'
  resources :ad_units do
    get 'show', :on => :member
  end

  get 'uploads/clear_all'
  resources :uploads do
    get 'download_errors', :on => :member
    get 'download_created', :on => :member
    get 'download_not_created', :on => :member    
  end
    
  root :to => 'whatelse#get_started'

end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :name, :uniqueness => {:scope => [:network_id, :advertiser_id]},
                   :length => { :in => 1..128 }
                   
  validates :po_number, :length => { :in => 1..63 }
  
  def self.params_dfp2bulk(params)
    p = params.dup
    p.de
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :ok }
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :advertiser_id %><br />
    <%= f.text_field :advertiser_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :trafficker_id %><br />
    <%= f.text_field :trafficker_id %>
  </div>
  <div class="field">
    <%= f.label :secondary_trafficker_id %><br />
    <%= f.text_field :secondary_trafficker_id %>
  </div>
  <div class="field">
    <%= f.label :sales_person_id %><br />
    <%= f.text_field :sales_person_id %>
  </div>
  <div class="field">
    <%= f.label :secondary_sales_person_id %><br />
    <%= f.text_field :secondary_sales_person_id %>
  </div>
  <div class="field">
    <%= f.label :agency_id %><br />
    <%= f.text_field :agency_id %>
  </div>
  <div class="field">
    <%= f.label :external_order_id %><br />
    <%= f.text_field :external_order_id %>
  </div>
  <div class="field">
    <%= f.label :po_number %><br />
    <%= f.text_field :po_number %>
  </div>
  <div class="field">
    <%= f.label :currency_code %><br />
    <%= f.text_field :currency_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>Advertiser</th>
    <th>Name</th>
    <th>Trafficker</th>
    <th>Secondary trafficker</th>
    <th>Sales person</th>
    <th>Secondary sales person</th>
    <th>Agency</th>
    <th>External order</th>
    <th>Po number</th>
    <th>Currency code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.advertiser_id %></td>
    <td><%= order.name %></td>
    <td><%= order.trafficker_id %></td>
    <td><%= order.secondary_trafficker_id %></td>
    <td><%= order.sales_person_id %></td>
    <td><%= order.secondary_sales_person_id %></td>
    <td><%= order.agency_id %></td>
    <td><%= order.external_order_id %></td>
    <td><%= order.po_number %></td>
    <td><%= order.currency_code %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Advertiser:</b>
  <%= @order.advertiser_id %>
</p>

<p>
  <b>Name:</b>
  <%= @order.name %>
</p>

<p>
  <b>Trafficker:</b>
  <%= @order.trafficker_id %>
</p>

<p>
  <b>Secondary trafficker:</b>
  <%= @order.secondary_trafficker_id %>
</p>

<p>
  <b>Sales person:</b>
  <%= @order.sales_person_id %>
</p>

<p>
  <b>Secondary sales person:</b>
  <%= @order.secondary_sales_person_id %>
</p>

<p>
  <b>Agency:</b>
  <%= @order.agency_id %>
</p>

<p>
  <b>External order:</b>
  <%= @order.external_order_id %>
</p>

<p>
  <b>Po number:</b>
  <%= @order.po_number %>
</p>

<p>
  <b>Currency code:</b>
  <%= @order.currency_code %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>