config/routes.rb
BulkUploader::Application.routes.draw do
  
  resources :orders

  get 'users/login'
  post 'users/login'
  
  get 'whatelse/get_started'
  get 'whatelse/error'
  get 'whatelse/download'
  
  get 'orders/index'
  get 'line_items/index'
  
  get 'companies/index'
  get 'companies/clear_all'
  get 'companies/download_all'
  get 'companies/copy_from_dfp'
  resources :companies do
    get 'show', :on => :member
  end

  get 'labels/index'
  get 'labels/clear_all'
  get 'labels/download_all'
  get 'labels/copy_from_dfp'
  resources :labels do
    get 'show', :on => :member
  end

  get 'ad_units/index'
  get 'ad_units/clear_all'
  get 'ad_units/download_all'
  get 'ad_units/copy_from_dfp'
  resources :ad_units do
    get 'show', :on => :member
  end

  get 'uploads/clear_all'
  resources :uploads do
    get 'download_errors', :on => :member
    get 'download_created', :on => :member
    get 'download_not_created', :on => :member    
  end
    
  root :to => 'whatelse#get_started'

end

app/models/company.rb
class Company < ActiveRecord::Base

  COMPANY_TYPES = ['ADVERTISER','AGENCY','HOUSE_ADVERTISER','HOUSE_AGENCY','AD_NETWORK']
  CREDIT_STATUS = ['ACTIVE','ON_HOLD', 'CREDIT_STOP', 'INACTIVE', 'BLOCKED']

  require 'csv'

  attr_accessor :label_list
  #TODO: name uniqueness scope? only among same type?
  validates :name, :presence => true, 
  :length => { :maximum => 127 }, 
  :uniqueness => { :case_sensitive => false,  :scope => [:network_id, :company_type] }
  validates :address, :length => { :maximum => 65535 }
  validates :email, :length => { :maximum => 127 }
  validates :fax_phone, :length => { :maximum => 63 } 
  validates :primary_phone, :length => { :maximum => 63 }
  validates :external_id, :length => { :maximum => 255 }
  validates :comment, :length => { :maximum => 1024 }
  validates_email_format_of :email, :allow_nil => true, :allow_blank => true

  validate :credit_status, :inclusion => { :in => Company::CREDIT_STATUS }
  validate :company_type_value_is_permitted
  validate :labels_exist

  has_and_belongs_to_many :labels
  accepts_nested_attributes_for :labels, :reject_if => :not_already_exists

  before_save :remove_trailing_spaces
  before_save :assign_defaults

  scope :nw, lambda { |network_id| where( :network_id => network_id) }

  def self.params_dfp2bulk(p)
    params = p.dup
    params[:company_type] = params.delete(:type)
    params[:dfp_id] = params.delete(:id).to_s
    params[:labels_attributes] = []

    unless params[:applied_labels].nil? 
      params[:applied_labels].each do |l|
        app_label = Label.find_by_dfp_id(l[:label_id])
        if app_label and !l[:is_negated]
          params[:labels_attributes] << { :name => app_label.name, :label_type => app_label.label_type }
        end
      end
    end
    params.delete(:applied_labels)
    return params
  end

  def params_bulk2dfp
    params = {}
    params[:name] = self.name
    params[:email] = self.email
    params[:type] = self.company_type
    params[:address] = self.address
    params[:fax_phone] = self.fax_phone
    params[:primary_phone] = self.primary_phone
    params[:comment] = self.comment
    params[:enable_same_advertiser_competitive_exclusion] = self.enable_same_advertiser_competitive_exclusion
    params[:applied_labels] = []
    params[:credit_status] = self.credit_status
    params[:applied_labels] = [] 
    self.labels.each do |l|
      params[:applied_labels] << {:label_id =>l.dfp_id, :is_negated => false}
    end
    return params
  end

  def self.row_to_params(row, nw_id)
    return nil if row.blank?

    params = {}

    params[:name] = row[0]
    params[:company_type] = row[1]
    params[:address] = row[2]
    params[:email] = row[3]
    params[:fax_phone] = row[4]
    params[:primary_phone] = row[5]
    params[:external_id] = row[6]
    params[:comment] = row[7]
    params[:enable_same_advertiser_competitive_exclusion] = row[8] || false
    params[:credit_status] = row[9]
    params[:network_id] = nw_id

    return params if row[10].blank?
    params[:labels_attributes] = []    
    #we assume that the format is "label1_name;label2_name;...;labeln_nameΩ
    CSV.parse_line(row[10], :col_sep => ';').each do |l|
      next if l.blank?
      dl = Label.find_or_initialize_by_name_and_label_type(l, 'COMPETITIVE_EXCLUSION')
      #no need to pass more attributes, as not_already_exists will look with these 2
      params[:labels_attributes] << { :name => dl.name, :label_type => dl.label_type } 
    end
    return params
  end

  def to_row
    row = [self.name, self.company_type, self.address, self.email, self.fax_phone, self.primary_phone, self.external_id, self.comment, 
      self.enable_same_advertiser_competitive_exclusion, self.credit_status]
    row << self.label_list
  end

  def exists?
    Company.find_by_name(self.name) ? true : false
  end

  def label_list
    return '' if self.labels.blank?
    ll = ''
    self.labels.each_with_index do |l, i|
      ll += l.name + ';'
    end
    return ll.chop!
  end

  def label_list=(llist)
    return if llist.blank?

    CSV.parse_line(llist, :col_sep => ';').each do |label_name|
      l = Label.find_or_initialize_by_name_and_label_type(label_name, 'COMPETITIVE_EXCLUSION')
      self.labels << l unless self.labels.include?(l)
    end
  end

  #Validations
  def company_type_value_is_permitted
    unless COMPANY_TYPES.include?(company_type)
      errors.add(:company_type, 'Value not permitted.')
    end
  end

  def labels_exist
    self.labels.each do |l|
      if l.new_record?
        errors.add(:labels, l.name + ': label does not exist')
      elsif l.label_type != 'COMPETITIVE_EXCLUSION'
        errors.add(:labels, l.name + ': label type not compatible')
      end
    end
  end

  def not_already_exists(params)
    l = Label.find_by_name_and_label_type( params[:name], params[:label_type] )
    if not self.labels.include?(l)
      self.labels << Label.find_or_initialize_by_name_and_label_type( params[:name], params[:label_type] ) 
    end
    return true
  end

  def remove_trailing_spaces
    self.name.chop! while self.name.last == ' '
    self.name.reverse!.chop!.reverse! while self.name.first == ' '
  end

  def assign_defaults
    self.credit_status = 'ACTIVE' if self.credit_status.blank?
  end

  def self.sort_all(companies)
    companies.sort! do |a,b|
      a.name <=> b.name
    end
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  require 'dfp_api'

  # GET /companies
  # GET /companies.json
  def index

    @companies = Company.nw(session[:nw]).all
    Company.sort_all(@companies)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        flash[:success] = 'Company was successfully created.'
        format.html { redirect_to @company }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])
    respond_to do |format|
      
      @company.update_attributes(params[:company])
      a=1
      if @company.save
        flash[:success] = 'Company was successfully updated.'
        format.html { redirect_to @company }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :ok }
    end
  end

  def sync_to_dfp
    
    if !Label.nw(session[:nw]).find_all_by_dfp_id(nil).blank?
      flash[:error] = 'There are Labels that are not uploaded to DFP. Please upload those DFP before proceeding with uploading of Companies.'
      redirect_to(companies_path)
    else
      super
    end
    
  end
  
  def download_all
    super
  end
  
  def copy_from_dfp
    super
  end
  
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= twitter_bootstrap_form_for(@company) do |f| %>
	<%= f.inputs do%>
    <%= f.text_field :name %>
    <%= f.select 'company_type', 'Company Type',
							 Company::COMPANY_TYPES,
				   		 :input_html => { :include_blank => false } %>
    <%= f.text_field :address %>
    <%= f.text_field :email %>
    <%= f.text_field :fax_phone %>
    <%= f.text_field :primary_phone %>
    <%= f.text_field :external_id %>
    <%= f.text_field :label_list %>
		<% f.toggles do %>
    	<%= f.check_box :enable_same_advertiser_competitive_exclusion %>
		<% end %>
    <%= f.text_area :comment, :rows => 4 %>
	<% end %>
	<%= f.actions do %>
    <%= f.submit %>
	<% end %>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Details', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<%= render 'layouts/action_bar'%>

<table class="zebra-striped bordered-table super-condensed-table"> 
  <thead>
		<tr>
	    <th>Name</th>
	    <th>Type</th>
	    <th>Labels</th>
	    <th>Uploaded to DFP?</th>
	    <th></th>
		</tr>
  </thead>
	<tbody>
		<% @companies.each do |company| %>
		  <tr>
		    <td><%= company.name %></td>
		    <td><%= company.company_type %></td>
			<td><%= company.label_list%></td>
		    <td><%= company.dfp_id.blank? ? "No" : "Yes" %></td>	
		    <td><%= link_to 'Details', company %></td>
		  </tr>
		<% end %>
	</tbody>
</table>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @company.name %>
</p>

<p>
  <b>Type:</b>
  <%= @company.company_type %>
</p>

<p>
  <b>Address:</b>
  <%= @company.address %>
</p>

<p>
  <b>Email:</b>
  <%= @company.email %>
</p>

<p>
  <b>Faxphone:</b>
  <%= @company.fax_phone %>
</p>

<p>
  <b>Primaryphone:</b>
  <%= @company.primary_phone %>
</p>

<p>
  <b>Externalid:</b>
  <%= @company.external_id %>
</p>

<p>
  <b>Comment:</b>
  <%= @company.comment %>
</p>

<p>
  <b>Enablesameadvertisercompetitiveexclusion:</b>
  <%= @company.enable_same_advertiser_competitive_exclusion %>
</p>

<p>
	<b>Labels:</b>
	<%= @company.label_list %>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>